language: php

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"
        - COMPOSER_FLAGS=""
    global:
        - secure: BoOyRHTRAUqkhXoju9xE0fRVm8/MHOlFZ+gobGVI/R/WYcvEUGsIJXfaHdF+KttCHjiJGVAJENSBk/cJR12BYxiev9uqdwXqcDYOj1OIwQYZgMVgq/7XyyHvhSGsxwY2kascv1cuZnQALpGxqeh4bwMH7HIyX394A1z/CfZoaMaIYjGzXeRYNE1/mOGMK8qgu/GBDFLJAv+XxL+gG46rb6M9m56J4g9NE8c6lnk2ylD2c6IR4OuDiNgPtxYqFIo+8iA4fExEUMCFkAxgYT4Qh1vNu2DgNTud5+QLT6dwUEGfhUODXW2Pu4f0BAg+fdsHIDg7MHxh0a+gBrJjvrv97uSN6JSRrwPMqe9PkfTnwCpS+pNztg5izz2BqoJT/9SFK7dLWBOoaHN1z60OPBe4VILYFdLhbv2h1sm+jVlMByun4htU7b/OnlJDT+ud0nbBk04jucPhoW3XMaJ6T2EQaJ6Q4nl10CUB7GQIYZuEcjv1X1P9EiKkosOs1iGHhA38biP/MZazS/Wmzu5MK/Emnd9Xz2hq+s8fTRgYfJUuqK4+1yGDnM2mTH/I0UwgDe+o/mV5WQJdSjc4ExWrxuKNJJxJwl361775mporhuyPleP96tn3P51C6dnQF88/kJ/l2LwkVro9mEApW0E2WViQ06l+lCcuiuazwPdKTQOZmoU=
        - secure: SuLHzTqd1CMUtlpsEFskaaMaWidT3mpXovivp+yE4hDXjnmadtV1DT5tfnuQeWOeK01zNSjDOGzI7erDQqJlCAzs8TZBcyMlhJ/1pYCAMZQDvBtRKL6WJ8xlP894st5xB03zo5blk6Jb5wm4jpFr97gFr5slRNA1eDprILmKz2nrgewRk5dBnHRZKJ4QU38ZZXAKHoaj0zXLYecSdM8nxxdbpuXPIkDAu+AHfPxfyX2Zv1KeVpgOYgF5ensIv6lgiG3yL6HF7bbUPR9YDjsNEURLKTydFiwDIZt7Dy1kFd5+kIVlq+Ye/3ja6thxLskK6nRtz9k03evkAFpb/toLKWedlCsDR+DsSGqo0CLHlHKrBYV64sYkif/xkljiIc9dAQj+oIaWqw+iCktF0UQv/9HUI344PAASlmRJ+UIhqz4CDfAk3ntYxZMHU2OGLTjkZ7ztvIQWk+LsSUgVqbhvV639eMv0Q35sgZ6MflNUL75RfdUFVQLWqY+KqOK+2GSCCGQilTIFoPzPF+0uEhh5h3PA3MKlIFSqPmrfvukmaOBKaEv5L1TjthMfaHNCV7aAodIQAjBpL3HgO9aPkjrxhZa+F3ooO3bjMxw6H7Q9oZYs3eM+A/zJHIdOIQmz8JEpXCFu4o9KpjrC2l3Jypp4EcEtZxVd5/U+W7C7VXEIQ0A=

jobs:
    allow_failures:
        - php: nightly

php:
    - nightly
    - 8.0
    - 7.4
    - 7.3
    - 7.2
    - 7.1

before_script:
    # Increase memory limit & disable xdebug
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - phpenv config-rm xdebug.ini

    # Authenticate Docker Hub
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

    # Update Composer to latest version & install dependencies
    - composer self-update
    - composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - composer test
    - bash scripts/boot.sh ${COMPOSER_FLAGS}

after_script:
    - composer upload-coverage
    - docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.Size}}'
